# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths

# use Ganache's forked mainnet mode as the default network
networks:
  # default: local
  default: heco

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.1
# brownie pm install OpenZeppelin/openzeppelin-contracts@3.4.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.5.16
    # version: 0.8.2
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.1"
  
console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true

reports:
  exclude_contracts:
    - SafeMath

